Repository Mala1180/PPS-22-satify, pull requests merged in 2023-09, with the labels that each got.

#67 Feature/gui-tab-improvement
  src/main/scala/satify/Main.scala
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/model/CNF.scala
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/model/problems/Problem.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Solver.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/TseitinTransformation.scala
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/satify/problems/NQueensTest.scala
Labels: chore, refactor

#66 Feature/automatic-changelog
  .github/workflows/release.yml
  CHANGELOG.md
Labels: documentation, ci

#71 Feature/reflection-bdd-test
  build.sbt
  src/main/scala/satify/dsl/Encodings.scala
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/model/expression/Encodings.scala
  src/test/resources/features/ReflectionTest.feature
  src/test/resources/features/TseitinTransformation.feature
  src/test/scala/satify/ExpressionUtilsTest/SatEncodingsTest.scala
  src/test/scala/satify/dsl/ReflectionTest.scala
  src/test/scala/satify/dsl/SatEncodingTest.scala
  src/test/scala/satify/features/ReflectionTest.scala
  src/test/scala/satify/features/TseitinTransformationSteps.scala
Labels: enhancement, test

#69 Feature/fix-input
  src/main/scala/satify/model/expression/Expression.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
Labels: fix

#70 Feature/input-error-handling
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/model/errors/Error.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/view/View.scala
Labels: chore

#72 Feature/documentation-update
  doc/report/1-methodology.md
  doc/report/2-requirements.md
  doc/report/README.md
Labels: documentation

#74 Feature/documentation-tseitin-impl
  doc/report/5-implementation.md
  doc/report/img/AndCircuit.svg
  doc/report/img/NotCircuit.svg
  doc/report/img/OrCircuit.svg
Labels: documentation

#75 Feature/gui-minor-fix
  src/main/scala/satify/Main.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
Labels: chore, fix

#73 Feature/requirements-refinement
  README.md
  doc/report/1-methodology.md
  doc/report/2-requirements.md
  doc/report/3-architectural-design.md
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/6-retrospective.md
  src/main/scala/satify/Architecture.scala
  src/main/scala/satify/Main.scala
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/model/dpll/DecisionTree.scala
  src/main/scala/satify/model/expression/Encodings.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/update/Solver.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/Converter.scala
  src/main/scala/satify/update/dpll/ConflictIdentification.scala
  src/main/scala/satify/update/dpll/DPLL.scala
  src/main/scala/satify/update/dpll/PartialModelUtils.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/test/scala/satify/DPLLTest/CNFSimplificationTest.scala
  src/test/scala/satify/DPLLTest/ConflictIdentificationTest.scala
  src/test/scala/satify/DPLLTest/DPLLTest.scala
  src/test/scala/satify/DPLLTest/PartialModelUtilsTest.scala
  src/test/scala/satify/ExpressionUtilsTest/CNFConverter.scala
  src/test/scala/satify/ExpressionUtilsTest/ExpressionOutputTest.scala
  src/test/scala/satify/ExpressionUtilsTest/ReplaceTest.scala
  src/test/scala/satify/ExpressionUtilsTest/SubexpressionsTest.scala
  src/test/scala/satify/ExpressionUtilsTest/VariableSubstitutionTest.scala
  src/test/scala/satify/parser/DimacsTest.scala
  src/test/scala/satify/problems/NQueensTest.scala
Labels: documentation, refactor

#76 Feature/solver-refactor
  doc/report/5-implementation.md
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/update/Solver.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/Converter.scala
  src/main/scala/satify/update/converters/ConverterType.scala
  src/main/scala/satify/update/converters/TseitinTransformation.scala
  src/main/scala/satify/update/solver/Solver.scala
  src/main/scala/satify/update/solver/SolverType.scala
  src/main/scala/satify/update/solver/dpll/CNFSimplification.scala
  src/main/scala/satify/update/solver/dpll/ConflictIdentification.scala
  src/main/scala/satify/update/solver/dpll/DPLL.scala
  src/main/scala/satify/update/solver/dpll/PartialModelUtils.scala
  src/test/scala/satify/features/TseitinTransformationSteps.scala
  src/test/scala/satify/problems/NQueensTest.scala
  src/test/scala/satify/update/converters/CNFConverter.scala
  src/test/scala/satify/update/converters/CNFOutputTest.scala
  src/test/scala/satify/update/converters/CNFValidator.scala
  src/test/scala/satify/update/converters/TseitinTest.scala
  src/test/scala/satify/update/converters/TseitinTransformationTest.scala
  src/test/scala/satify/update/converters/VariableSubstitutionTest.scala
  src/test/scala/satify/update/solver/dpll/CNFSimplificationTest.scala
  src/test/scala/satify/update/solver/dpll/ConflictIdentificationTest.scala
  src/test/scala/satify/update/solver/dpll/DPLLTest.scala
  src/test/scala/satify/update/solver/dpll/PartialModelUtilsTest.scala
Labels: documentation, test, breaking change, refactor

#79 Feature/tseitin-transform-refactor
  src/main/scala/satify/update/converters/TseitinTransformation.scala
  src/test/scala/satify/update/converters/TseitinTransformationTest.scala
Labels: chore, refactor

#81 Feature/update-organization
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/update/Update.scala
Labels: refactor

#80 Feature/converter-memoize
  src/main/scala/satify/update/converters/Converter.scala
Labels: enhancement

#83 Feature/solver-cache
  doc/report/5-implementation.md
  src/main/scala/satify/update/solver/Solver.scala
Labels: performance

#85 Feature/tseitin-bdd-test
  doc/report/5-implementation.md
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/model/cnf/CNF.scala
  src/main/scala/satify/model/dpll/DecisionTree.scala
  src/main/scala/satify/model/dpll/PartialModel.scala
  src/main/scala/satify/model/expression/Expression.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/Converter.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/converters/tseitin/Utils.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/update/solver/Solver.scala
  src/main/scala/satify/update/solver/dpll/Dpll.scala
  src/main/scala/satify/update/solver/dpll/Optimizations.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSat.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSimplification.scala
  src/main/scala/satify/update/solver/dpll/utils/DpllUtils.scala
  src/main/scala/satify/update/solver/dpll/utils/PartialModelUtils.scala
  src/main/scala/satify/view/View.scala
  src/test/resources/features/Reflection.feature
  src/test/resources/features/TseitinTransformation.feature
  src/test/scala/satify/features/ReflectionSteps.scala
  src/test/scala/satify/features/TseitinTransformationSteps.scala
  src/test/scala/satify/model/cnf/CNFOutputTest.scala
  src/test/scala/satify/model/expression/ExpressionOutputTest.scala
  src/test/scala/satify/model/expression/ReplaceTest.scala
  src/test/scala/satify/model/expression/SatEncodingsTest.scala
  src/test/scala/satify/model/expression/SatEncodingsWrongUseTest.scala
  src/test/scala/satify/parser/DimacsTest.scala
  src/test/scala/satify/update/converters/tseitin/ConcatTest.scala
  src/test/scala/satify/update/converters/tseitin/ReplacingTest.scala
  src/test/scala/satify/update/converters/tseitin/TransformationTest.scala
  src/test/scala/satify/update/converters/tseitin/TseitinTest.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFConverter.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFValidator.scala
  src/test/scala/satify/update/converters/tseitin/utils/ZippingTest.scala
  src/test/scala/satify/update/solver/dpll/CNFSatTest.scala
  src/test/scala/satify/update/solver/dpll/CNFSimplificationTest.scala
  src/test/scala/satify/update/solver/dpll/DpllTest.scala
  src/test/scala/satify/update/solver/dpll/PartialModelUtilsTest.scala
Labels: test, refactor

#86 Feature/tailrec-parser-cnf-refactor
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/model/cnf/CNF.scala
  src/main/scala/satify/model/dpll/PartialModel.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/converters/tseitin/Utils.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/update/solver/dpll/Dpll.scala
  src/main/scala/satify/update/solver/dpll/Optimizations.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSat.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSimplification.scala
  src/main/scala/satify/update/solver/dpll/utils/PartialModelUtils.scala
  src/test/scala/satify/model/cnf/CNFOutputTest.scala
  src/test/scala/satify/model/expression/ReplaceTest.scala
  src/test/scala/satify/parser/DimacsTest.scala
  src/test/scala/satify/update/converters/tseitin/ConcatTest.scala
  src/test/scala/satify/update/converters/tseitin/ReplacingTest.scala
  src/test/scala/satify/update/converters/tseitin/TransformationTest.scala
  src/test/scala/satify/update/converters/tseitin/TseitinTest.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFConverter.scala
  src/test/scala/satify/update/converters/tseitin/utils/ZippingTest.scala
  src/test/scala/satify/update/solver/dpll/CNFSatTest.scala
  src/test/scala/satify/update/solver/dpll/CNFSimplificationTest.scala
  src/test/scala/satify/update/solver/dpll/DpllTest.scala
  src/test/scala/satify/update/solver/dpll/PartialModelUtilsTest.scala
Labels: chore, refactor

#87 Feature/problem-representation
  src/main/scala/satify/Main.scala
  src/main/scala/satify/model/expression/Encodings.scala
  src/main/scala/satify/model/problems/GraphColoring.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/model/problems/NurseScheduling.scala
  src/main/scala/satify/model/problems/Problem.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/test/scala/satify/problems/NQueensTest.scala
  src/test/scala/satify/update/ConvertUpdateTest.scala
  src/test/scala/satify/update/ImportUpdateTest.scala
  src/test/scala/satify/update/NextSolutionUpdateTest.scala
  src/test/scala/satify/update/SolveProblemUpdateTest.scala
Labels: enhancement, refactor

#88 Feature/dimacs-dump
  src/main/scala/satify/Main.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/satify/parser/DumpTest.scala
  src/test/scala/satify/parser/ParseTest.scala
Labels: chore

#90 Feature/encoding-completion
  src/main/scala/satify/dsl/Encodings.scala
  src/main/scala/satify/model/expression/Encodings.scala
  src/main/scala/satify/model/expression/Utils.scala
  src/main/scala/satify/model/problems/GraphColoring.scala
  src/main/scala/satify/model/problems/NurseScheduling.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/solver/dpll/utils/PartialModelUtils.scala
  src/test/resources/features/Reflection.feature
  src/test/scala/satify/dsl/SatEncodingTest.scala
  src/test/scala/satify/model/expression/ExpressionOutputTest.scala
  src/test/scala/satify/model/expression/SatEncodingsTest.scala
  src/test/scala/satify/model/expression/SatEncodingsWrongUseTest.scala
Labels: test, chore, performance

#91 Feature/next-sol-mechanism
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/solver/Solver.scala
  src/main/scala/satify/update/solver/dpll/Dpll.scala
  src/main/scala/satify/update/solver/dpll/DpllDecision.scala
  src/main/scala/satify/update/solver/dpll/DpllOneSol.scala
  src/main/scala/satify/update/solver/dpll/utils/DpllUtils.scala
  src/test/scala/satify/update/NextSolutionUpdateTest.scala
  src/test/scala/satify/update/solver/dpll/DpllOneSolTest.scala
  src/test/scala/satify/update/solver/dpll/DpllTest.scala
  src/test/scala/satify/update/solver/dpll/PartialModelUtilsTest.scala
Labels: enhancement

#95 Feature/end-sprint-4
  doc/process/3-product-backlog.md
  doc/process/4-product-backlog.md
Labels: documentation

#98 Feature/product-backlog-5
  doc/process/5-product-backlog.md
Labels: documentation

#94 Feature/dpll-refactor
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/model/dpll/DecisionTree.scala
  src/main/scala/satify/model/dpll/OptionalVariable.scala
  src/main/scala/satify/model/dpll/PartialAssignment.scala
  src/main/scala/satify/model/dpll/PartialModel.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/update/solver/Solver.scala
  src/main/scala/satify/update/solver/dpll/Dpll.scala
  src/main/scala/satify/update/solver/dpll/DpllDecision.scala
  src/main/scala/satify/update/solver/dpll/DpllOneSol.scala
  src/main/scala/satify/update/solver/dpll/Optimizations.scala
  src/main/scala/satify/update/solver/dpll/utils/DpllUtils.scala
  src/main/scala/satify/update/solver/dpll/utils/PartialModelUtils.scala
  src/test/scala/satify/model/dpll/PartialAssignmentTest.scala
  src/test/scala/satify/problems/NQueensTest.scala
  src/test/scala/satify/update/parser/DumpTest.scala
  src/test/scala/satify/update/parser/ParseTest.scala
  src/test/scala/satify/update/solver/dpll/DpllOneSolTest.scala
  src/test/scala/satify/update/solver/dpll/DpllTest.scala
  src/test/scala/satify/update/solver/dpll/PartialModelUtilsTest.scala
  src/test/scala/satify/update/solver/dpll/cnf/CNFSatTest.scala
  src/test/scala/satify/update/solver/dpll/cnf/CNFSimplificationTest.scala
Labels: refactor

#96 Feature/export-improvement
  doc/report/2-requirements.md
  doc/report/5-implementation.md
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/satify/update/parser/DumpTest.scala
Labels: documentation, chore

#97 Feature/show-comp-time
  doc/report/2-requirements.md
  src/main/scala/satify/Main.scala
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/Utils.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
Labels: chore

#99 Feature/solution-fetching-all-assignments
  src/main/scala/satify/Main.scala
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/solver/Solver.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllEnumerator.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllFinder.scala
  src/main/scala/satify/update/solver/dpll/utils/DpllUtils.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/satify/problems/NQueensTest.scala
  src/test/scala/satify/update/solver/dpll/impl/DpllEnumeratorTest.scala
  src/test/scala/satify/update/solver/dpll/impl/DpllFinderTest.scala
Labels: enhancement, chore

#101 Feature/scalameter-intro
  build.sbt
  src/test/scala/satify/scalameter/problems/nqueens/MemoryBenchmark.scala
  src/test/scala/satify/scalameter/problems/nqueens/SolvingBenchmark.scala
Labels: benchmark

#104 Feature/tseitin-ordering-clauses
  src/main/scala/satify/model/expression/Expression.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/test/scala/satify/model/expression/ExpressionUtilsTest.scala
  src/test/scala/satify/update/converters/tseitin/ReplacingTest.scala
  src/test/scala/satify/update/converters/tseitin/TseitinTest.scala
Labels: chore

#103 Feature/help-refinement
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/Constants.scala
Labels: chore

#107 Feature/fix-dpll-enumerator-solve-all
  src/main/scala/satify/update/solver/dpll/impl/DpllEnumerator.scala
Labels: fix

#102 Feature/cache-repl
  src/main/scala/satify/Main.scala
  src/main/scala/satify/dsl/Reflection.scala
  src/test/scala/satify/update/ConvertUpdateTest.scala
Labels: refactor, performance

#105 Feature/next-sol-problem-fix
  src/main/scala/satify/update/Update.scala
Labels: fix

#106 Feature/gui-input-expression-style
  src/main/scala/satify/Main.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/main/scala/satify/view/utils/ComponentUtils.scala
  src/main/scala/satify/view/utils/TextPaneUtils.scala
Labels: chore

#109 Feature/nqueen-representation
  src/main/scala/satify/model/problems/GraphColoring.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/model/problems/NurseScheduling.scala
  src/main/scala/satify/model/problems/Problem.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/main/scala/satify/view/utils/ComponentUtils.scala
  src/test/scala/satify/problems/NQueensTest.scala
Labels: chore

#111 Feature/show-time-next-sol
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/Utils.scala
  src/main/scala/satify/view/View.scala
Labels: chore

#112 Feature/fix-style-cucumber-steps
  src/test/scala/satify/features/DSLSteps.scala
  src/test/scala/satify/features/TseitinTransformationSteps.scala
Labels: test, refactor

#115 Feature/magic-string
  src/main/scala/satify/Main.scala
  src/main/scala/satify/model/dpll/PartialAssignment.scala
  src/main/scala/satify/model/errors/Error.scala
  src/main/scala/satify/model/problems/Problem.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/converters/tseitin/Utils.scala
  src/main/scala/satify/update/solver/dpll/DpllDecision.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllFinder.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/main/scala/satify/view/utils/ComponentUtils.scala
  src/main/scala/satify/view/utils/ProblemTitle.scala
  src/main/scala/satify/view/utils/TextPaneUtils.scala
  src/main/scala/satify/view/utils/Title.scala
Labels: documentation

#119 Feature/tseitin-little-fix
  src/main/scala/satify/model/dpll/PartialAssignment.scala
  src/main/scala/satify/model/expression/SymbolGeneration.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/converters/tseitin/Utils.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllFinder.scala
  src/test/resources/features/Conversion.feature
  src/test/resources/features/TseitinTransformation.feature
  src/test/scala/satify/features/ConversionSteps.scala
  src/test/scala/satify/update/converters/tseitin/ConcatTest.scala
  src/test/scala/satify/update/converters/tseitin/ReplacingTest.scala
  src/test/scala/satify/update/converters/tseitin/TransformationTest.scala
  src/test/scala/satify/update/converters/tseitin/TseitinTest.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFConverter.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFValidator.scala
  src/test/scala/satify/update/converters/tseitin/utils/ZippingTest.scala
Labels: fix

#122 Feature/solver-bdd-refactor
  doc/report/2-requirements.md
  src/main/scala/satify/model/Solution.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/solver/Solver.scala
  src/main/scala/satify/update/solver/dpll/DpllDecision.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllEnumerator.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllFinder.scala
  src/main/scala/satify/view/View.scala
  src/test/resources/features/Solver.feature
  src/test/scala/satify/features/SatEncodingsSteps.scala
  src/test/scala/satify/features/SolverSteps.scala
  src/test/scala/satify/problems/NQueensTest.scala
  src/test/scala/satify/update/solver/dpll/impl/DpllEnumeratorTest.scala
  src/test/scala/satify/update/solver/dpll/impl/DpllFinderTest.scala
Labels: test, refactor

#127 Feature/refinement-chores
  README.md
  doc/process/4-product-backlog.md
  doc/process/5-product-backlog.md
  src/main/scala/satify/model/cnf/CNF.scala
  src/main/scala/satify/model/errors/Error.scala
  src/main/scala/satify/model/expression/Encodings.scala
  src/main/scala/satify/model/expression/Expression.scala
  src/main/scala/satify/model/problems/GraphColoring.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/model/problems/NurseScheduling.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/solver/dpll/DpllDecision.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllFinder.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/main/scala/satify/view/utils/ComponentUtils.scala
  src/main/scala/satify/view/utils/TextPaneUtils.scala
  src/test/resources/features/Solving.feature
  src/test/scala/satify/features/SolverSteps.scala
  src/test/scala/satify/model/cnf/CNFOutputTest.scala
  src/test/scala/satify/model/expression/ExpressionUtilsTest.scala
  src/test/scala/satify/model/expression/ReplaceTest.scala
  src/test/scala/satify/model/problems/ProblemWrongUseTest.scala
  src/test/scala/satify/problems/GraphColoringTest.scala
  src/test/scala/satify/problems/NQueensTest.scala
  src/test/scala/satify/problems/NurseSchedulingTest.scala
  src/test/scala/satify/update/ConvertUpdateTest.scala
  src/test/scala/satify/update/ImportUpdateTest.scala
  src/test/scala/satify/update/NextSolutionUpdateTest.scala
  src/test/scala/satify/update/SolveProblemUpdateTest.scala
  src/test/scala/satify/update/converters/tseitin/ConcatTest.scala
  src/test/scala/satify/update/converters/tseitin/ReplacingTest.scala
  src/test/scala/satify/update/converters/tseitin/TseitinTest.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFConverter.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFValidator.scala
  src/test/scala/satify/update/converters/tseitin/utils/ZippingTest.scala
Labels: test, chore, refactor

#126 Feature/converter-design
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/6-retrospective.md
  doc/report/img/cnf/cnf.png
  doc/report/img/converter/converter.png
  doc/report/img/problem/problem.png
Labels: documentation

#130 Feature/ref-tseitin-method
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/test/scala/satify/update/converters/tseitin/ReplacingTest.scala
Labels: refactor

#135 Feature/auto-doc-ci
  .github/workflows/release.yml
  .github/workflows/scaladoc.yml
Labels: ci

#136 Feature/fix-auto-scaladoc
  .github/workflows/scaladoc.yml
Labels: ci

#139 Feature/microbenchmarking
  src/test/scala/satify/update/converters/tseitin/benchmark/ConversionMemoryBenchmark.scala
  src/test/scala/satify/update/converters/tseitin/benchmark/ConversionProblemBenchmark.scala
  src/test/scala/satify/update/converters/tseitin/benchmark/MemoryBenchmark.scala
  src/test/scala/satify/update/solver/dpll/benchmark/MemoryBenchmark.scala
  src/test/scala/satify/update/solver/dpll/benchmark/SolvingBenchmark.scala
  src/test/scala/satify/update/solver/dpll/benchmark/SolvingMemoryBenchmark.scala
  src/test/scala/satify/update/solver/dpll/benchmark/SolvingProblemBenchmark.scala
Labels: benchmark

#142 Feature/doc-update-methodology-requirements
  doc/report/1-methodology.md
  doc/report/2-requirements.md
  doc/report/4-detailed-design.md
  doc/report/README.md
Labels: documentation

#137 Feature/tailrec-optimizations-par-assignment
  src/main/scala/satify/model/solver/PartialAssignment.scala
  src/main/scala/satify/update/solver/dpll/Optimizations.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSat.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSimplification.scala
  src/main/scala/satify/update/solver/dpll/impl/DpllFinder.scala
  src/main/scala/satify/update/solver/dpll/utils/PartialAssignmentUtils.scala
  src/test/scala/satify/update/SolveProblemUpdateTest.scala
Labels: fix, performance

#146 Feature/implementation-doc-tseitin
  doc/diagrams/mvu/mvu-detailed.drawio
  doc/diagrams/mvu/mvu-detailed.png
  doc/diagrams/mvu/mvu-detailed.puml
  doc/diagrams/mvu/mvu.drawio
  doc/report/3-architectural-design.md
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/img/converter/converter.png
  doc/report/img/converter/converter.svg
  doc/report/img/mvu-detailed.svg
  doc/report/img/mvu.png
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/converters/tseitin/Utils.scala
  src/test/scala/satify/update/converters/tseitin/SubtitutionsTest.scala
  src/test/scala/satify/update/converters/tseitin/utils/CNFConverter.scala
Labels: documentation

#145 Feature/doc-benchmark-and-update
  doc/api/satify/model/cnf/CNF$.html
  doc/api/satify/model/cnf/CNF.html
  doc/api/satify/model/expression/Utils$.html
  doc/api/scripts/searchData.js
  doc/report/2-requirements.md
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/img/packages.svg
  doc/report/img/problem/problem.png
  doc/report/img/problem/problem.svg
  src/main/scala/satify/model/cnf/CNF.scala
  src/main/scala/satify/model/expression/Utils.scala
  src/main/scala/satify/model/problems/GraphColoring.scala
  src/main/scala/satify/model/problems/NQueens.scala
  src/main/scala/satify/model/problems/NurseScheduling.scala
  src/main/scala/satify/model/problems/Problem.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/view/View.scala
  src/test/resources/features/DSL.feature
  src/test/scala/satify/features/ConversionSteps.scala
  src/test/scala/satify/features/DSLSteps.scala
  src/test/scala/satify/model/cnf/CNFOutputTest.scala
  src/test/scala/satify/model/expression/ExpressionOutputTest.scala
  src/test/scala/satify/update/converters/tseitin/benchmark/ConversionMemoryBenchmark.scala
  src/test/scala/satify/update/converters/tseitin/benchmark/ConversionProblemBenchmark.scala
  src/test/scala/satify/update/solver/dpll/benchmark/SolvingMemoryBenchmark.scala
  src/test/scala/satify/update/solver/dpll/benchmark/SolvingProblemBenchmark.scala
Labels: documentation, refactor

#143 Feature/doc-detailed-design-dpll
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/img/cnf/cnf.svg
  doc/report/img/cnfsimpl/And1.svg
  doc/report/img/cnfsimpl/And2.svg
  doc/report/img/cnfsimpl/AndCircuit.svg
  doc/report/img/cnfsimpl/NotCircuit.svg
  doc/report/img/cnfsimpl/OrCircuit.svg
  doc/report/img/cnfsimpl/cOr1.svg
  doc/report/img/cnfsimpl/cOr2.svg
  doc/report/img/cnfsimpl/umOr1.svg
  doc/report/img/cnfsimpl/umOr2.svg
  doc/report/img/cnfsimpl/umOr3.svg
  doc/report/img/cnfsimpl/umOr4.svg
  doc/report/img/converter/converter.svg
  doc/report/img/dpll.png
  doc/report/img/exp/exp.svg
  doc/report/img/mvu-detailed.svg
  doc/report/img/packages.svg
  doc/report/img/problem/problem.svg
  doc/report/img/solution.svg
  doc/report/img/solver/dpll-decision.svg
  doc/report/img/solver/solver.svg
  doc/report/img/solver/solver_design.svg
Labels: documentation

#148 Feature/dsl-chore
  doc/api/satify/dsl/Reflection$.html
  doc/report/1-methodology.md
  doc/report/2-requirements.md
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/README.md
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/model/expression/Encodings.scala
Labels: documentation, chore

#149 Feature/final-doc-refinement
  doc/process/1-product-backlog.md
  doc/process/2-product-backlog.md
  doc/process/3-product-backlog.md
  doc/process/4-product-backlog.md
  doc/process/5-product-backlog.md
  doc/report/1-methodology.md
  doc/report/2-requirements.md
  doc/report/3-architectural-design.md
  doc/report/4-detailed-design.md
  doc/report/5-implementation.md
  doc/report/6-retrospective.md
  doc/report/README.md
  doc/report/img/cnf/cnf.svg
  doc/report/img/cnfsimpl/cnfsimpl.svg
  doc/report/img/exp/exp.svg
  doc/report/img/mvu.png
  doc/report/img/mvu/mvu-detailed.svg
  doc/report/img/mvu/mvu.svg
  doc/report/img/solution.svg
  doc/report/img/solver/solver_design.svg
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/model/problems/NurseScheduling.scala
  src/main/scala/satify/model/solver/PartialAssignment.scala
  src/main/scala/satify/update/converters/Converter.scala
  src/main/scala/satify/update/converters/tseitin/TseitinTransformation.scala
  src/main/scala/satify/update/converters/tseitin/Utils.scala
  src/main/scala/satify/update/solver/dpll/Optimizations.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSat.scala
  src/main/scala/satify/update/solver/dpll/cnf/CNFSimplification.scala
  src/main/scala/satify/update/solver/dpll/utils/PartialAssignmentUtils.scala
  src/test/scala/satify/model/expression/ExpressionOutputTest.scala
  src/test/scala/satify/model/expression/ExpressionUtilsTest.scala
  src/test/scala/satify/model/problems/ProblemWrongUseTest.scala
  src/test/scala/satify/update/SolveProblemUpdateTest.scala
  src/test/scala/satify/update/converters/tseitin/benchmark/ConversionProblemBenchmark.scala
Labels: documentation

#152 Release/1.0.0
  .github/workflows/changelog.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: release
