Repository Mala1180/PPS-22-satify, pull requests merged in 2023-08, with the labels that each got.

#33 Feature/dpll-conflict-identification
  src/main/scala/satify/model/dpll/DecisionTree.scala
  src/main/scala/satify/update/dpll/CNFSimplification.scala
  src/main/scala/satify/update/dpll/ConflictIdentification.scala
  src/main/scala/satify/update/dpll/DPLL.scala
  src/main/scala/satify/update/dpll/PartialModelUtils.scala
  src/test/scala/satify/DPLLTest/CNFSimplificationTest.scala
  src/test/scala/satify/DPLLTest/ConflictIdentificationTest.scala
  src/test/scala/satify/DPLLTest/DPLLTest.scala
  src/test/scala/satify/DPLLTest/PartialModelUtilsTest.scala
  src/test/scala/satify/DecisionTreeTest/DPLLTest.scala
Labels: breaking change

#34 Feature/end-sprint-2
  doc/process/1-product-backlog.md
  doc/process/2-product-backlog.md
  doc/report/3-architectural-design.md
  doc/report/README.md
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/view/GUI.scala
Labels: documentation, enhancement

#38 Feature/dpll-unit-propagation
  src/main/scala/satify/model/CNF.scala
  src/main/scala/satify/update/dpll/CNFSimplification.scala
  src/main/scala/satify/update/dpll/ConflictIdentification.scala
  src/main/scala/satify/update/dpll/DPLL.scala
  src/main/scala/satify/update/dpll/PartialModelUtils.scala
  src/test/scala/satify/DPLLTest/CNFSimplificationTest.scala
  src/test/scala/satify/DPLLTest/ConflictIdentificationTest.scala
  src/test/scala/satify/DPLLTest/DPLLTest.scala
  src/test/scala/satify/DPLLTest/PartialModelUtilsTest.scala
Labels: chore

#36 Feature/backlog-sprint-3
  doc/process/2-product-backlog.md
  doc/process/3-product-backlog.md
Labels: documentation

#37 Feature/sbt-assembly
  .github/workflows/ci.yml
  README.md
  project/plugins.sbt
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/Constants.scala
  test
Labels: dependencies

#42 Feature/dsl-math-operators
  src/main/scala/satify/dsl/DSL.scala
  src/main/scala/satify/update/Update.scala
  src/test/scala/satify/dsl/BasicOperatorsTest.scala
  src/test/scala/satify/dsl/MathOperatorsTest.scala
  src/test/scala/satify/dsl/SimpleOperatorsTest.scala
Labels: enhancement, test

#44 Feature/complete-model
  src/main/scala/satify/dsl/DSL.scala
  src/main/scala/satify/model/Problem.scala
  src/main/scala/satify/model/State.scala
  src/test/scala/satify/dsl/MathOperatorsTest.scala
Labels: chore

#45 Feature/gui-refactor
  src/main/scala/satify/Architecture.scala
  src/main/scala/satify/Main.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/satify/ExpressionUtilsTest/SubexpressionsTest.scala
  src/test/scala/satify/TestArchitecture.scala
Labels: refactor

#39 Feature/dpll-pure-literals-elimination
  src/main/scala/satify/model/dpll/DecisionTree.scala
  src/main/scala/satify/model/dpll/PartialModel.scala
  src/main/scala/satify/update/dpll/CNFSimplification.scala
  src/main/scala/satify/update/dpll/ConflictIdentification.scala
  src/main/scala/satify/update/dpll/DPLL.scala
  src/main/scala/satify/update/dpll/PartialModelUtils.scala
  src/test/scala/satify/DPLLTest/CNFSimplificationTest.scala
  src/test/scala/satify/DPLLTest/ConflictIdentificationTest.scala
  src/test/scala/satify/DPLLTest/DPLLTest.scala
  src/test/scala/satify/DPLLTest/PartialModelUtilsTest.scala
Labels: chore

#48 Feature/import-dimacs
  src/main/resources/cnf/aim-100-1_6-no-1.txt
  src/main/scala/satify/Main.scala
  src/main/scala/satify/model/CNF.scala
  src/main/scala/satify/model/Expression.scala
  src/main/scala/satify/update/Message.scala
  src/main/scala/satify/update/Solver.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/update/dpll/CNFSimplification.scala
  src/main/scala/satify/update/dpll/ConflictIdentification.scala
  src/main/scala/satify/update/dpll/DPLL.scala
  src/main/scala/satify/update/parser/Dimacs.scala
  src/main/scala/satify/view/ComponentUtils.scala
  src/main/scala/satify/view/Constants.scala
  src/main/scala/satify/view/GUI.scala
  src/main/scala/satify/view/Reactions.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/parser/DimacsTest.scala
  src/test/scala/satify/ExpressionUtilsTest/OutputTest.scala
Labels: enhancement

#49 Feature/sat-encodings
  src/main/scala/satify/dsl/Conversion.scala
  src/main/scala/satify/dsl/DSL.scala
  src/main/scala/satify/dsl/Numbers.scala
  src/main/scala/satify/dsl/Operators.scala
  src/main/scala/satify/dsl/SatEncodings.scala
  src/main/scala/satify/model/Expression.scala
  src/test/scala/satify/dsl/SatEncodingsTest.scala
  src/test/scala/satify/dsl/SatEncodingsWrongUseTest.scala
Labels: enhancement, test, refactor

#51 Feature/dsl-implications
  src/main/scala/satify/Main.scala
  src/main/scala/satify/dsl/Operators.scala
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/dsl/SatEncodings.scala
  src/main/scala/satify/model/Expression.scala
  src/main/scala/satify/model/State.scala
  src/main/scala/satify/update/Update.scala
  src/main/scala/satify/view/View.scala
  src/test/scala/satify/dsl/MathOperatorsTest.scala
  src/test/scala/satify/dsl/OperatorsTest.scala
Labels: documentation, enhancement, test, refactor

#53 Feature/tseitin-transformations-fix
  src/main/scala/satify/update/converters/TseitinTransformation.scala
  src/test/resources/features/TseitinTransformation.feature
  src/test/resources/features/todo.feature
  src/test/scala/satify/ExpressionUtilsTest/CNFConverter.scala
  src/test/scala/satify/ExpressionUtilsTest/CNFValidator.scala
  src/test/scala/satify/ExpressionUtilsTest/TseitinTest.scala
  src/test/scala/satify/dsl/MathOperatorsTest.scala
  src/test/scala/satify/dsl/OperatorsTest.scala
  src/test/scala/steps/TseitinTransformation.scala
Labels: fix

#55 Feature/fix-dsl-reflection
  build.sbt
  src/main/scala/satify/dsl/Conversion.scala
  src/main/scala/satify/dsl/Reflection.scala
  src/main/scala/satify/dsl/SatEncodings.scala
  src/test/scala/satify/dsl/ReflectionTest.scala
Labels: test, refactor, fix

#54 Feature/documentation-improvement
  doc/report/1-methodology.md
  doc/report/2-requirements.md
  doc/report/3-architectural-design.md
  doc/report/4-detailed-design.md
  doc/report/6-retrospective.md
  doc/report/README.md
Labels: documentation

#56 fix: import reflection
  src/main/scala/satify/dsl/Reflection.scala
Labels: fix

#60 Feature/cucumber-plugin
  .github/workflows/ci.yml
  .github/workflows/release.yml
  build.sbt
  project/plugins.sbt
  src/main/scala/satify/dsl/Reflection.scala
  src/test/resources/cucumber.properties
  src/test/resources/features/Example.feature
  src/test/scala/satify/features/TseitinTransformationSteps.scala
  src/test/scala/satify/parser/DimacsTest.scala
  src/test/scala/steps/ExampleCucumberSteps.scala
Labels: ci, test, dependencies
